[tool.ruff.lint]
extend-select = [
    "F",
    "E",
    "N",
    "C90",
    "I",
    "W",
    "UP",
    "PLR",
    "B",
    "SIM",
    "ANN",
    "BLE",
    "S",
    "A",
    "C4",
    "EXE",
    "ICN",
    "LOG",
    "G",
    "PIE",
    "RSE",
    "RET",
    "TCH",
    "ARG",
    "PL",
    "FLY",
    "RUF",
    # "PD",
]
extend-ignore = [
    "E501",
    "PLR0911",
    "SIM108",
    "ANN201",
    "C408",
    "S113",
    "RET504",
]
